config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users

  get 'foreign_relationships/follow_new_people', as: "follow_new_people"
  get 'foreign_relationships/unfollow_current_people', as: "unfollow_current_people"
  resources :foreign_relationships, path: 'foreign-relationships'

  get 'foreign_likes/like_foreign_users_media', as: "like_foreign_users_media"
  resources :foreign_likes, path: 'foreign-likes'

  resources :foreign_users, path: 'foreign-users'

  get '/dashboard' => redirect('/')

  get 'oauth/connect', as: 'oauth_connect'
  get 'oauth/callback', as: 'oauth_callback'

  root to: redirect('/foreign-users')

end

app/models/foreign_user.rb
class ForeignUser < ActiveRecord::Base

  has_many :foreign_likes
  has_one :foreign_relationship

  #scopes
  scope :following, lambda { where(['following IS TRUE']) }
  scope :not_private, lambda { where(['is_private IS NOT TRUE']) }
  scope :has_follows, lambda { where(['follows > 0']) }
  scope :has_enough_follows, lambda { where(['follows > 5']) }
  scope :older_than_two_weeks, lambda { where(['created_at < ?', 14.days.ago]) }


  ############################
  #
  # Actions
  #
  ############################

  # create user in system
  def create_foreign_user_in_system(foreign_user_id, client)
    return create_foreign_user_in_system(foreign_user_id, client)
  end
  def self.create_foreign_user_in_system(foreign_user_id, client)

    # look for user
    test_user = ForeignUser.where(foreign_id: foreign_user_id).first

    if test_user != nil
      return test_user
    end

    user = client.user(foreign_user_id)

    user_data = {}
    user_data[:foreign_id] = user.id
    user_data[:foreign_username] = user.username
    user_data[:foreign_full_name] = user.full_name
    user_data[:media] = user.counts.media
    user_data[:follows] = user.counts.follows
    user_data[:followed_by] = user.counts.followed_by

    return foreign_user = ForeignUser.create_with(user_data).find_or_create_by!(foreign_id: user.id)
  end


  # create foreign private user
  def create_foreign_private_user_in_system(foreign_user_id, foreign_username)
    return create_foreign_private_user_in_system(foreign_user_id, foreign_username)
  end
  def self.create_foreign_private_user_in_system(foreign_user_id, foreign_username)
    return ForeignUser.create(foreign_id: foreign_user_id, is_private: true, foreign_username: foreign_username)
  end

  # get follow
  def get_followers(foreign_user_id, client)
    return get_followers(foreign_user_id, client)
  end
  def self.get_followers(foreign_user_id, client)
    return client.user_follows(foreign_user_id)
  end

  # get followed_by
  def get_followed_by(foreign_user_id, client)
    return get_followed_by(foreign_user_id, client)
  end
  def self.get_followed_by(foreign_user_id, client)
    return client.user_followed_by(foreign_user_id)
  end

  # exsisting?
  def existing?
    if self.not_existing === true
      return false
    else
      return true
    end
  end
  def self.existing?
    existing?
  end
end

app/controllers/foreign_users_controller.rb
class ForeignUsersController < ApplicationController
  before_action :set_foreign_user, only: [:show, :edit, :update, :destroy]

  # GET /foreign_users
  # GET /foreign_users.json
  def index
    @page_count = params[:page]
    @foreign_users = current_user.foreign_users.page(@page_count).per(50)
    @all_foreign_users = current_user.foreign_users
  end

  # GET /foreign_users/1
  # GET /foreign_users/1.json
  def show
  end

  # GET /foreign_users/new
  def new
    @foreign_user = ForeignUser.new
  end

  # GET /foreign_users/1/edit
  def edit
  end

  # POST /foreign_users
  # POST /foreign_users.json
  def create
    @foreign_user = ForeignUser.new(foreign_user_params)

    respond_to do |format|
      if @foreign_user.save
        format.html { redirect_to @foreign_user, notice: 'Foreign user was successfully created.' }
        format.json { render :show, status: :created, location: @foreign_user }
      else
        format.html { render :new }
        format.json { render json: @foreign_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foreign_users/1
  # PATCH/PUT /foreign_users/1.json
  def update
    respond_to do |format|
      if @foreign_user.update(foreign_user_params)
        format.html { redirect_to @foreign_user, notice: 'Foreign user was successfully updated.' }
        format.json { render :show, status: :ok, location: @foreign_user }
      else
        format.html { render :edit }
        format.json { render json: @foreign_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foreign_users/1
  # DELETE /foreign_users/1.json
  def destroy
    @foreign_user.destroy
    respond_to do |format|
      format.html { redirect_to foreign_users_url, notice: 'Foreign user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foreign_user
      @foreign_user = ForeignUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foreign_user_params
      params.require(:foreign_user).permit(:foreign_id, :foreign_username, :foreign_full_name, :media, :follows, :followed_by, :following, :is_private, :not_existing)
    end
end

app/helpers/foreign_users_helper.rb
module ForeignUsersHelper
end

app/views/foreign_users/_form.html.erb
<%= form_for(@foreign_user) do |f| %>
  <% if @foreign_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foreign_user.errors.count, "error") %> prohibited this foreign_user from being saved:</h2>

      <ul>
      <% @foreign_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :foreign_id %><br>
    <%= f.number_field :foreign_id %>
  </div>
  <div class="field">
    <%= f.label :foreign_username %><br>
    <%= f.text_field :foreign_username %>
  </div>
  <div class="field">
    <%= f.label :foreign_full_name %><br>
    <%= f.text_field :foreign_full_name %>
  </div>
  <div class="field">
    <%= f.label :media %><br>
    <%= f.number_field :media %>
  </div>
  <div class="field">
    <%= f.label :follows %><br>
    <%= f.number_field :follows %>
  </div>
  <div class="field">
    <%= f.label :followed_by %><br>
    <%= f.number_field :followed_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foreign_users/edit.html.erb
<h1>Editing Foreign User</h1>

<%= render 'form' %>

<%= link_to 'Show', @foreign_user %> |
<%= link_to 'Back', foreign_users_path %>

app/views/foreign_users/index.html.erb
<div class="page-header">
  <h1>
    Foreign Users
    <small>(<%= @all_foreign_users.following.count %>/<%= @all_foreign_users.count %>)</small>
  </h1>
</div>

<%= paginate @foreign_users, :theme => 'twitter-bootstrap-3'%>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Foreign</th>
        <th>Foreign username</th>
        <th>Foreign full name</th>
        <th>Following</th>
        <th>Private</th>
        <th>Media</th>
        <th>Follows</th>
        <th>Followed by</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @foreign_users.each do |foreign_user| %>
        <tr>
          <td><%= foreign_user.foreign_id %></td>
          <td><%= foreign_user.foreign_username %></td>
          <td><%= foreign_user.foreign_full_name %></td>
          <td><%= foreign_user.following %></td>
          <td><%= foreign_user.is_private %></td>
          <td><%= foreign_user.media %></td>
          <td><%= foreign_user.follows %></td>
          <td><%= foreign_user.followed_by %></td>
          <td><%#= link_to 'Show', foreign_user %></td>
          <td><%#= link_to 'Edit', edit_foreign_user_path(foreign_user) %></td>
          <td><%#= link_to 'Destroy', foreign_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @foreign_users, :theme => 'twitter-bootstrap-3'%>

app/views/foreign_users/new.html.erb
<h1>New Foreign User</h1>

<%= render 'form' %>

<%= link_to 'Back', foreign_users_path %>

app/views/foreign_users/show.html.erb
<p>
  <strong>Foreign:</strong>
  <%= @foreign_user.foreign_id %>
</p>

<p>
  <strong>Foreign username:</strong>
  <%= @foreign_user.foreign_username %>
</p>

<p>
  <strong>Foreign full name:</strong>
  <%= @foreign_user.foreign_full_name %>
</p>

<p>
  <strong>Media:</strong>
  <%= @foreign_user.media %>
</p>

<p>
  <strong>Follows:</strong>
  <%= @foreign_user.follows %>
</p>

<p>
  <strong>Followed by:</strong>
  <%= @foreign_user.followed_by %>
</p>

<%= link_to 'Edit', edit_foreign_user_path(@foreign_user) %> |
<%= link_to 'Back', foreign_users_path %>