config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users

  get 'foreign_relationships/follow_new_people', as: "follow_new_people"
  get 'foreign_relationships/unfollow_current_people', as: "unfollow_current_people"
  resources :foreign_relationships, path: 'foreign-relationships'

  get 'foreign_likes/like_foreign_users_media', as: "like_foreign_users_media"
  resources :foreign_likes, path: 'foreign-likes'

  resources :foreign_users, path: 'foreign-users'

  get '/dashboard' => redirect('/')

  get 'oauth/connect', as: 'oauth_connect'
  get 'oauth/callback', as: 'oauth_callback'

  root to: redirect('/foreign-users')

end

app/models/foreign_like.rb
class ForeignLike < ActiveRecord::Base

  belongs_to :foreign_user

  # like images of people the user recently followed with the system
  def self.like_foreign_users_images(current_user, client)
    # get random 5 public foreign users within the last 80
    selected_foreign_users = current_user.foreign_users.not_private.order("created_at DESC").limit(80).sample(5)
    access_token = client.access_token

    # loop foreign users
    for foreign_user in selected_foreign_users do

      # get 3 to 5 recent photos # URL
      foreign_user_media_url = "https://api.instagram.com/v1/users/#{foreign_user.foreign_id}/media/recent/?access_token=#{access_token}"

      # get remote json
      resp = Net::HTTP.get_response(URI.parse(foreign_user_media_url))
      data = resp.body
      data = JSON.parse(data)

      # save photos
      photos = data["data"].take(2)

      # only if we got some
      if photos.count > 0

        # loop photos
        for photo in photos
          photo_id = photo["id"]

          # like photo
          begin
            client.like_media(photo_id)
            # mark photo as liked
            foreignlike = ForeignLike.add_foreign_like(photo_id, foreign_user.foreign_id, foreign_user.id, current_user)
          rescue => e
            return handle_instagram_api_error(e, nil)
          end
        end
      end
    end

    return "Liked some Photos."
  end



  # add foreign relation for the foreign user follow
  def self.add_foreign_like(foreign_media_id, foreign_user_id, user_id, creator)
    ForeignLike.create(
      foreign_media_id: foreign_media_id,
      foreing_user_id: foreign_user_id,
      user_id: user_id,
      liked_at: DateTime.now,
      creator_id: creator.id,
      updater_id: creator.id
    )
  end




  # instagram/faraday error handling
  def self.handle_instagram_api_error(e, *args)
    error_class = e.class
    error_string = e.to_s
    error_return = "An error occured: #{error_class}"
    args = args.first

    logger.debug "ERROR: #{error_class}, #{error_string}, #{args}"

    # internal error
    if error_class == Instagram::InternalServerError
      return error_return = "There was an internal instagram error."
    end

    # too many requests
    if error_class == Instagram::TooManyRequests
      attampts = error_string.split(/ /)[16]
      return error_return = "You've reached the hourly maximum set by Instagram (#{attampts}/20). Try again later."
    end

    # not able to see the user
    if error_class == Instagram::BadRequest
    end
  end

end

app/controllers/foreign_likes_controller.rb
class ForeignLikesController < ApplicationController
  before_action :set_foreign_like, only: [:show, :edit, :update, :destroy]

  # GET /foreign_likes
  # GET /foreign_likes.json
  def index
    @page_count = params[:page]
    @foreign_likes = current_user.foreign_likes.page(@page_count).per(50)
    @all_foreign_likes = current_user.foreign_likes
  end

  # GET /foreign_likes/1
  # GET /foreign_likes/1.json
  def show
  end

  # GET /foreign_likes/new
  def new
    @foreign_like = ForeignLike.new
  end

  # GET /foreign_likes/1/edit
  def edit
  end

  # POST /foreign_likes
  # POST /foreign_likes.json
  def create
    @foreign_like = ForeignLike.new(foreign_like_params)

    respond_to do |format|
      if @foreign_like.save
        format.html { redirect_to @foreign_like, notice: 'Foreign like was successfully created.' }
        format.json { render :show, status: :created, location: @foreign_like }
      else
        format.html { render :new }
        format.json { render json: @foreign_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foreign_likes/1
  # PATCH/PUT /foreign_likes/1.json
  def update
    respond_to do |format|
      if @foreign_like.update(foreign_like_params)
        format.html { redirect_to @foreign_like, notice: 'Foreign like was successfully updated.' }
        format.json { render :show, status: :ok, location: @foreign_like }
      else
        format.html { render :edit }
        format.json { render json: @foreign_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foreign_likes/1
  # DELETE /foreign_likes/1.json
  def destroy
    @foreign_like.destroy
    respond_to do |format|
      format.html { redirect_to foreign_likes_url, notice: 'Foreign like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like_foreign_users_media
    LikeImages.schedule!
    redirect_to foreign_likes_path, notice: "Photos will be liked."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foreign_like
      @foreign_like = ForeignLike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foreign_like_params
      params.require(:foreign_like).permit(:foreign_media_id, :foreing_user_id, :user_id, :liked_at, :unliked_at)
    end
end

app/helpers/foreign_likes_helper.rb
module ForeignLikesHelper
end

app/views/foreign_likes/_form.html.erb
<%= form_for(@foreign_like) do |f| %>
  <% if @foreign_like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foreign_like.errors.count, "error") %> prohibited this foreign_like from being saved:</h2>

      <ul>
      <% @foreign_like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :foreign_media_id %><br>
    <%= f.number_field :foreign_media_id %>
  </div>
  <div class="field">
    <%= f.label :foreing_user_id %><br>
    <%= f.number_field :foreing_user_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :liked_at %><br>
    <%= f.datetime_select :liked_at %>
  </div>
  <div class="field">
    <%= f.label :unliked_at %><br>
    <%= f.datetime_select :unliked_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foreign_likes/edit.html.erb
<h1>Editing Foreign Like</h1>

<%= render 'form' %>

<%= link_to 'Show', @foreign_like %> |
<%= link_to 'Back', foreign_likes_path %>

app/views/foreign_likes/index.html.erb
<div class="page-header">
  <h1>
    Foreign Likes
    <small>(<%= @all_foreign_likes.count %>)</small>
  </h1>
</div>

<%= paginate @foreign_likes, :theme => 'twitter-bootstrap-3'%>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Foreign media</th>
        <th>Foreing user</th>
        <th>User</th>
        <th>Liked at</th>
        <th>Unliked at</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @foreign_likes.each do |foreign_like| %>
        <tr>
          <td><%= foreign_like.foreign_media_id %></td>
          <td><%= foreign_like.foreing_user_id %></td>
          <td><%= foreign_like.user_id %></td>
          <td><%= foreign_like.liked_at %></td>
          <td><%= foreign_like.unliked_at %></td>
          <td><%#= link_to 'Show', foreign_like %></td>
          <td><%#= link_to 'Edit', edit_foreign_like_path(foreign_like) %></td>
          <td><%#= link_to 'Destroy', foreign_like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @foreign_likes, :theme => 'twitter-bootstrap-3'%>

app/views/foreign_likes/new.html.erb
<h1>New Foreign Like</h1>

<%= render 'form' %>

<%= link_to 'Back', foreign_likes_path %>

app/views/foreign_likes/show.html.erb
<p>
  <strong>Foreign media:</strong>
  <%= @foreign_like.foreign_media_id %>
</p>

<p>
  <strong>Foreing user:</strong>
  <%= @foreign_like.foreing_user_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @foreign_like.user_id %>
</p>

<p>
  <strong>Liked at:</strong>
  <%= @foreign_like.liked_at %>
</p>

<p>
  <strong>Unliked at:</strong>
  <%= @foreign_like.unliked_at %>
</p>

<%= link_to 'Edit', edit_foreign_like_path(@foreign_like) %> |
<%= link_to 'Back', foreign_likes_path %>