config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users

  get 'foreign_relationships/follow_new_people', as: "follow_new_people"
  get 'foreign_relationships/unfollow_current_people', as: "unfollow_current_people"
  resources :foreign_relationships, path: 'foreign-relationships'

  get 'foreign_likes/like_foreign_users_media', as: "like_foreign_users_media"
  resources :foreign_likes, path: 'foreign-likes'

  resources :foreign_users, path: 'foreign-users'

  get '/dashboard' => redirect('/')

  get 'oauth/connect', as: 'oauth_connect'
  get 'oauth/callback', as: 'oauth_callback'

  root to: redirect('/foreign-users')

end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><%= notice %></p>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><%= alert %></p>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><i class="fa fa-instagram"></i> Push</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%= navigation_li_link "Users", foreign_users_path %>
          <%= navigation_li_link "Relations", foreign_relationships_path %>
          <%= navigation_li_link "Likes", foreign_likes_path %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user.instagram_access_token %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Actions <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to "Follow", follow_new_people_path %>
                </li>
                <li>
                  <%= link_to "Like Photos", like_foreign_users_media_path %>
                </li>
                <li>
                  <%= link_to "Unfollow", unfollow_current_people_path %>
                </li>
              </ul>
            </li>
          <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.display_name %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% if current_user.instagram_username %>
                <li>
                  <a href="https://www.instagram.com/<%= current_user.instagram_username %>" target="_blank">Show Instagram</a>
                </li>
              <% end %>
              <li><%= link_to "Settings", edit_user_path(id: current_user.id) %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        </ul>

        <% unless current_user.instagram_access_token %>
          <a class="btn btn-default navbar-btn pull-right" href="/oauth/connect"><i class="fa fa-instagram"></i> Connect with Instagram</a>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaPush</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale = 1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' if current_user %>
    <div class="container">
      <%= render 'layouts/alerts' %>
      <%= yield %>
    </div>
  </body>
</html>